version: '3'

services:
  front-end-app:
    image: explore-london-react:latest
    container_name: explore-london-react
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_BACKEND_BASE_URL: "localhost:8080/api"
    volumes:
      - ./frontend:/app
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        - REACT_APP_BACKEND_BASE_URL=localhost:8080/api

  mongoDb:
    image: mongo
    container_name: explore-london-mongo
    restart: always
    ports:
      - "27017:27017"

  mongo-seed-1:
    build: ./backend/mongo-seed-1
    depends_on:
      - mongoDb

  mongo-seed-2:
    build: ./backend/mongo-seed-2
    depends_on:
      - mongoDb

  back-end:
    image: explore-london-express:latest
    container_name: explore-london-express
    ports:
      - "8080:8080"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      MONGO_URL: "mongodb://mongodb:27017/"
      LOCAL_MODE: "true"
    volumes:
      - ./backend:/app
    build:
      context: ./backend
      dockerfile: Dockerfile
