version: '3'

services:
  front-end-app-prod:
    image: explore-london-react-prod:latest
    container_name: explore-london-prod-react
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_BASE_URL=explore-london-discovery-service.explore-london.backend

  back-end-prod:
    image: explore-london-express-prod:latest
    container_name: explore-london-prod-express
    ports:
      - "8080:8080"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./backend:/app
    build:
      context: ./backend
      dockerfile: Dockerfile
